{% set name = "pyaimnet2" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jthorton/AIMNet2/archive/refs/tags/{{ version }}.tar.gz
  sha256: 36983094d5cf91f1583b0c9a9b757534a438eb210a392c9e31ed2903bbd20432

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  build:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - pytorch =2.0.0

test:
  imports:
    - pyaimnet2

  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jthorton/AIMNet2
  summary: 'AIMNet2: a general-purpose neural network potential for organic and element-organic molecules.'
  description: |
    The repository contains AIMNet2 ensemble models only and a convince method to load the models via python, see the original repository for all models.
    The models are applicable for systems containing the following set of chemical elements: {H, B, C, N, O, F, Si, P, S, Cl, As, Se, Br, I}, both neutral and charged. 
    The models aim to reproduce RKS B97-3c and wB97M-D3 energies.
    The models are in the form of JIT-compiled PyTorch-2.0 files and could be loaded in Python or C++ code.
    Note, that at present models have O(N^2) compute and memory complexity w.r.t. number of atoms. They could be applied to systems up to a few 100's of atoms.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/jthorton/AIMNet2
  dev_url: https://github.com/jthorton/AIMNet2

extra:
  recipe-maintainers:
    - jthorton
